### ISSUE TITLE
PyCharm `.idea` directory not in `.gitignore`

### ISSUE THREAD

**Issue by johanzietsman-em** [Ex-Mente/auxi.0#185]
### Background
PyCharm adds a `.idea` directory to the root of projects. This directory should never arrive in the GitHub repository. It should therefore be included in the `.gitignore` file.

### Purpose
Add `.idea` to the `.gitignore` file.

**Comment by alchemyst** [comment]
There is currently a spyder project file in the repository. Perhaps we should make an issue to remove that as well?
