### ISSUE TITLE
MAKE-RELEASES.md update Travis deploy trigger procedure.

### ISSUE THREAD

**Issue by christoffkok** [Ex-Mente/auxi.0#96]
#### Background
Travis.CI automatically deploy `auxi` to PyPi if the previous commit was tagged in Git. Tagging a release is part of our release procedure. GitHub does this as well when someone creates a release. Currently the documented strategy on how tag a release does not work.
#### Purpose
The purpose of this issue is to add to the documentation how to tag a commit for a release such that Travis.CI will automatically trigger a PyPi deploy when the release is submitted to the master branch.
#### Approach
In the documentation, describe how to tag a release via the GitHub user interface method.

**Comment by johanzietsman-em** [comment]
The background is not clear. Please describe it clearly so that other project members can understand. Let's discuss.
